name: Build and Run Test Application Workflow

on:
  schedule:
    - cron: '0 0 * * *' # (scheduled - once per day at midnight)
  pull_request: # (for every push to Pull Request)
    types: [opened, reopened, synchronize]
  workflow_dispatch:  # (to start the workflow manually)

jobs:
  build_project:
    name: Build Project
    uses: ./.github/workflows/build_esp_app.yml
  test_in_wokwi:
    name: Test Project (Wokwi Simulation)
    uses: ./.github/workflows/test_in_wokwi.yml
    needs: build_project
    secrets:
      WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
  # Disable this job if you don't use it for hardware testing
  test_project_hw:
    if: ${{ github.repository_owner == 'espressif' }}  # Disable this job as default except if the repo is owned by Espressif
    name: Test Project (Hardware)
    uses: ./.github/workflows/test_esp_app.yml
    needs: build_project
  test_project_host_linux:
    name: Test Project (Host, linux-target)
    uses: ./.github/workflows/test_linux_target.yml
    needs: build_project
