name: Build and test WOKWI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-wokwi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Test Application with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: "latest" # latest is the default version
          target: esp32
          path: 'test_app'

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          expect_text: 'Mean'
